# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0003_auto_20160725_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='room_scheduling.Reservation'),
            preserve_default=False,
        ),
    ]
