# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0004_room_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reservation',
        ),
    ]
