# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0005_remove_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='room_scheduling.Room'),
            preserve_default=False,
        ),
    ]
