# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0007_auto_20160725_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'sunday'), (1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thusday'), (5, 'friday'), (6, 'saturday')], null=True),
        ),
    ]
