# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0008_reservation_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'sunday'), (1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday')], null=True),
        ),
    ]
