# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0010_reservation_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'sunday'), (1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday')], null=True),
        ),
    ]
