# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0011_auto_20160801_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], null=True),
        ),
    ]
