# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_scheduling', '0012_auto_20160801_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
